import * as React from "react";
import * as jQuery from "jquery";
import CommentForm from "../src/CommentForm";
import CommentList from "../src/CommentList"

class CommentBox extends React.Component<any,any> {

    constructor(props:any){
        super(props);
        this.state = { data: []};
    }
    public loadCommentsFromServer(){
        let self = this;
        //noinspection TypeScriptUnresolvedVariable
        jQuery.ajax({
            url: self.props.url,
            dataType: 'json',
            cache: false,
            success: function (data) {
                self.setState({data: data})
            },
            error: function (xhr, status, err) {
                //noinspection TypeScriptUnresolvedVariable
                console.error(self.props.url, status, err.toString())
            }
        });
    }
    public handleCommentSubmit(comment:any){
        let self = this;
        let comments = this.state.data;

        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        let newComments = comments.concat([comment]);
        this.setState({data: newComments});

        //noinspection TypeScriptUnresolvedVariable
        jQuery.ajax({
            url: this.props.url,
            dataType: 'json',
            type: 'POST',
            data: comment,
            success: function (data) {
                self.setState({data: data})
            },
            error: function (xhr, status, err) {
                self.setState({data: comments});
                //noinspection TypeScriptUnresolvedVariable
                console.error(self.props.url, status, err.toString())
            }
        });
    }
    public componentDidMount() {
        this.loadCommentsFromServer();
        //noinspection TypeScriptUnresolvedVariable
        setInterval(this.loadCommentsFromServer,this.props.pollInterval);
    }
    public render(){
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList data={this.state.data}/>
                <CommentForm onCommentSubmit={this.handleCommentSubmit.bind(this)}/>
            </div>
        );
    }
}

export default CommentBox;